logging:
  level:
    org:
      springframwork: debug

server:
  port: 8000



spring:
  datasource:

    url: jdbc:mysql://localhost:3306/projectn
    username: root
    password: 84948494

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
